### ISSUE TITLE
0688923 - Support for multiple placement groups, so that AutoScaling can be deployed in 2-3 AZs within a region

### ISSUE THREAD

**Issue by JaydenLiang** [fortinet/fortigate-autoscale-azure#45]
internal bug id: 0688923

- [ ] explicitly set vmss zoneBalance to false
- [ ] support vmss multi-availability zone deployment options
- [ ] support vmss palcement group options

**Comment by nahimos** [comment]
Hello 

I tried to use the code and i got the error like the template is not availaible : https://raw.githubusercontent.com/fortinet/fortigate-autoscale-azure/main/templates/link_template.vmss.json

**Comment by JaydenLiang** [comment]
> Hello
> 
> I tried to use the code and i got the error like the template is not availaible : https://raw.githubusercontent.com/fortinet/fortigate-autoscale-azure/main/templates/link_template.vmss.json

Hi @nahimos , this change is sill under development so the link will not be finalized until a release it created.
You can try this dev pre-release at this moment: https://github.com/fortinet/fortigate-autoscale-azure/releases/tag/3.3.3-merge15397.4, it includes this change.

**Comment by nahimos** [comment]
Hello @JaydenLiang  i h've tried the dev release: 3.3.3-merge15397.4 i got issue with the creation of the loadbalancer and fonction  app , see below the issues : 
For LB : 
"status": "Failed",
    "error": {
        "code": "LinkedInvalidPropertyId",
        "message": "L'ID de propriété « rcph-pubip » sur le chemin « properties.frontendIPConfigurations[0].properties.publicIPAddress.id » n'est pas valide. Un ID de ressource complet commençant par « /subscriptions/{subscriptionId} » ou « /providers/{resourceProviderNamespace}/ » est attendu."
    }
}

For Function App:

{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "Au moins une opération de déploiement de ressource a échoué. Listez les opérations de déploiement pour plus de détails. Consultez https://aka.ms/DeployOperations pour les détails d'utilisation.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidTemplate\",\r\n    \"message\": \"La validation du modèle de déploiement a échoué : « The template 'copy' definition at line '2' and column '3' has an invalid copy count. The copy count must be a positive integer value and cannot exceed '800'. Please see https://aka.ms/arm-copy for usage details. ».\",\r\n    \"additionalInfo\": [\r\n      {\r\n        \"type\": \"TemplateViolation\",\r\n        \"info\": {\r\n          \"lineNumber\": 2,\r\n          \"linePosition\": 3,\r\n          \"path\": \"[0]\"\r\n        }\r\n      }\r\n    ]\r\n  }\r\n}"
            }
        ]
    }
}

**Comment by JaydenLiang** [comment]
> Hello @JaydenLiang i h've tried the dev release: 3.3.3-merge15397.4 i got issue with the creation of the loadbalancer and fonction app , see below the issues :
> For LB :
> "status": "Failed",
> "error": {
> "code": "LinkedInvalidPropertyId",
> "message": "L'ID de propriété « rcph-pubip » sur le chemin « properties.frontendIPConfigurations[0].properties.publicIPAddress.id » n'est pas valide. Un ID de ressource complet commençant par « /subscriptions/{subscriptionId} » ou « /providers/{resourceProviderNamespace}/ » est attendu."
> }
> }
> 
> For Function App:
> 
> {
> "status": "Failed",
> "error": {
> "code": "DeploymentFailed",
> "message": "Au moins une opération de déploiement de ressource a échoué. Listez les opérations de déploiement pour plus de détails. Consultez https://aka.ms/DeployOperations pour les détails d'utilisation.",
> "details": [
> {
> "code": "BadRequest",
> "message": "{\r\n "error": {\r\n "code": "InvalidTemplate",\r\n "message": "La validation du modèle de déploiement a échoué : « The template 'copy' definition at line '2' and column '3' has an invalid copy count. The copy count must be a positive integer value and cannot exceed '800'. Please see https://aka.ms/arm-copy for usage details. ».",\r\n "additionalInfo": [\r\n {\r\n "type": "TemplateViolation",\r\n "info": {\r\n "lineNumber": 2,\r\n "linePosition": 3,\r\n "path": "[0]"\r\n }\r\n }\r\n ]\r\n }\r\n}"
> }
> ]
> }
> }

did you specify the ID of public IP?
how many subnets you intended to create in the vnet?

**Comment by nahimos** [comment]
The ID of the public IP is the name ? i put rcph-pubip.
I tried to create 4 subnets . it is possible to have only 1 subnet for the firewall and just use udr for the backend to reach the fortigate.
Also wheni use the template on the portal , the vmss create but the azure fonction doesn't work
Firewalls doesnt get the licence and the config

**Comment by JaydenLiang** [comment]
> The ID of the public IP is the name ? i put rcph-pubip.

No. talking about the public IP that is the 'Frontend IP Address ID' in the parameter, you need to give the fully qualified resource ID of it if you are going to use an existing IP address resource. If you leave it blank, it creates a new public IP resource for you.

> I tried to create 4 subnets . it is possible to have only 1 subnet for the firewall and just use udr for the backend to reach the fortigate.
Also wheni use the template on the portal , the vmss create but the azure fonction doesn't work
Firewalls doesnt get the licence and the config

To help me get a better insight, can you provide a copy of the input from your template deployment results? (remove sensitive input data before providing them)

**Comment by nahimos** [comment]
i left it blank. because i was looking for a new ip 
i will try another deployment and get back to you with the result

**Comment by nahimos** [comment]
I just tried the deployment again with the version  https://github.com/fortinet/fortigate-autoscale-azure/releases/tag/3.3.3-merge15397.4
i got the fonction app error : 
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "Au moins une opération de déploiement de ressource a échoué. Listez les opérations de déploiement pour plus de détails. Consultez https://aka.ms/DeployOperations pour les détails d'utilisation.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidTemplate\",\r\n    \"message\": \"La validation du modèle de déploiement a échoué : « The template 'copy' definition at line '2' and column '3' has an invalid copy count. The copy count must be a positive integer value and cannot exceed '800'. Please see https://aka.ms/arm-copy for usage details. ».\",\r\n    \"additionalInfo\": [\r\n      {\r\n        \"type\": \"TemplateViolation\",\r\n        \"info\": {\r\n          \"lineNumber\": 2,\r\n          \"linePosition\": 3,\r\n          \"path\": \"[0]\"\r\n        }\r\n      }\r\n    ]\r\n  }\r\n}"
            }
        ]
    }
}

**Comment by nahimos** [comment]
Tried the version dev release: 3.3.3-merge15397.5 also and i got the same function app failure while deploying 👍 
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "Au moins une opération de déploiement de ressource a échoué. Listez les opérations de déploiement pour plus de détails. Consultez https://aka.ms/DeployOperations pour les détails d'utilisation.",
        "details": [
            {
                "code": "NotFound",
                "message": "{\r\n  \"code\": \"NotFound\",\r\n  \"message\": \"Entity with the specified id does not exist in the system. More info: https://aka.ms/cosmosdb-tsg-not-found\\r\\nActivityId: 2a8f2ca9-0b57-41eb-b96b-cbf1110a642c, Microsoft.Azure.Documents.Common/2.14.0\"\r\n}"
            }
        ]
    }
}

**Comment by JaydenLiang** [comment]
Hi @nahimos , since I don't know the input of your template parameter, I can hardly tell what went wrong in your deployment.

**Comment by nahimos** [comment]
Hello @JaydenLiang  i found the issue, it is linked to right given to the azure function.
Thanks for your help the deployment work

**Comment by nahimos** [comment]
Hello Fortinet Team,

Do you have the roadmap for the next official release including this feature?
