### ISSUE TITLE
deploy without internal load blancer

### ISSUE THREAD

**Issue by JaydenLiang** [fortinet/fortigate-autoscale-azure#48]
The use of internal load balancer should be optional.
To provide a more general use case, we no longer assume the need of the internal load balancer so will remove it from our template.
Users can add the internal lb themselves after deployment.

However, the external load balancer associated with the FortiGate vmss is still an essential component.

**Comment by nahimos** [comment]
Hello Jayden
I'm looking for a deployement of a VMSS for Est-West traffic, the internet connection is then not needed for this firewalls, is it possible to : 
- either do a deployement and then delete the external loadbalancer ? 
- either do a deployement without external lb
Is this case is in your roadmap?

**Comment by JaydenLiang** [comment]
> Hello @JaydenLiang
> I'm looking for a deployment of a VMSS for Est-West traffic, the internet connection is then not needed for this firewalls,so there is no interest of external lb, is it possible to :
> 
> * either do a deployement and then delete the external loadbalancer ?
> * either do a deployement without external lb
>   Is this case is in your roadmap?

>  either do a deployement and then delete the external loadbalancer ?
yes. you can do it do deassociate the subnet1 and vmss from the external load balancer.

> either do a deployement without external lb ?
no, not for this project. external lb is by design. you can deassociate it after deployment completed. The elb in this project is provided for web (http, https) service protection using the FortiGate vmss. If you don't need it, it can be easily deassociated.

**Comment by nahimos** [comment]
@JaydenLiang  Thanks  for your confirmation, we will move forward and deassociate it. I guess that this deassociation won't affect next software upgrade for exemple.
Do you know when the new release will be publish (including multizone availability deployment)?
