### ISSUE TITLE
deploy autoscale resource in autoscale rsg instead of exiting vnet resource group

### ISSUE THREAD

**Issue by JaydenLiang** [fortinet/fortigate-autoscale-azure#50]
to better organize the autoscale resoruces, deploy them into the autoscale resource group instead of the vnet resource group.

the reasons are:
1. we offer the capability to deploy autoscale with existing vnet resources and the vnet resource group may be a complex environment that includes a lot different resources. It makes it much difficult to remove / upgrade the autoscale resources.

2. as we improve the Autoscale templates, now it's possible to do a better cross-resource group deployment within the same region.

**Comment by nahimos** [comment]
Hello @JaydenLiang  do know when the new release will be published?
